import type { Metadata } from "next";
import { Roboto_Mono, Montserrat, Cabin_Sketch } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const cabin = Cabin_Sketch({
  variable: "--font-cabin",
  weight: ['400', '700']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoMono.variable} ${montserrat.variable} ${cabin.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
